# Generated by Django 4.2.7 on 2023-11-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_seller'),
        ('user_management', '0003_sellermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Buyer'), ('2', 'Seller')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='SellerModel',
        ),
    ]
