# Generated by Django 4.2.7 on 2023-11-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_usermodel_user_type_delete_sellermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Deleted')], default=0, max_length=12),
        ),
    ]
