# Generated by Django 4.2.7 on 2023-11-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_usermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Deleted')], default='0', max_length=12),
        ),
    ]
