# Generated by Django 4.2.7 on 2023-11-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0006_usermodel_deleted_at_alter_usermodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="phone_number",
            field=models.CharField(default=123456789, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
