# Generated by Django 4.2.7 on 2023-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, through='core.CartItem', to='core.product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='category_products', to='core.product'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
    ]
