# Generated by Django 4.2.7 on 2023-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productvariation_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-20:00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='status',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Deleted')], default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-20:00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='status',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Deleted')], default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
