# Generated by Django 4.2.7 on 2023-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_created_at_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
